// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0H875YYQJt8yvMyZJx3Li_XR-fGcX1pI',
    appId: '1:640043129439:web:f94cedc3390e8e312719ea',
    messagingSenderId: '640043129439',
    projectId: 'mocsmunch-9adb3',
    authDomain: 'mocsmunch-9adb3.firebaseapp.com',
    storageBucket: 'mocsmunch-9adb3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcsEYbWNaOzGbyBs1Ns-AQcJR_c32SZYE',
    appId: '1:640043129439:android:54c31dd3e4038d012719ea',
    messagingSenderId: '640043129439',
    projectId: 'mocsmunch-9adb3',
    storageBucket: 'mocsmunch-9adb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHhXNaQ4t-ByGc37obPWiUCTCsy3hhlZU',
    appId: '1:640043129439:ios:fe37355c3ec6d71b2719ea',
    messagingSenderId: '640043129439',
    projectId: 'mocsmunch-9adb3',
    storageBucket: 'mocsmunch-9adb3.appspot.com',
    iosBundleId: 'com.example.mocsmunchv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHhXNaQ4t-ByGc37obPWiUCTCsy3hhlZU',
    appId: '1:640043129439:ios:c7998ce2e175dbcc2719ea',
    messagingSenderId: '640043129439',
    projectId: 'mocsmunch-9adb3',
    storageBucket: 'mocsmunch-9adb3.appspot.com',
    iosBundleId: 'com.example.mocsmunchv2.RunnerTests',
  );
}
